### PR TITLE
#6155: Penscratch 2: Add spacing controls for blocks

### LINKED ISSUE #6155: Older Themes: Buttons block missing Dimensions section
### Quick summary

The Buttons block seems to be missing Dimensions section when Edin theme is active.

### Steps to reproduce

1. Activate the Edin theme.
2. Add a Button block.
3. Check block settings sidebar.

### What you expected to happen

The Dimensions section should appear as shown in documentation: https://wordpress.com/support/wordpress-editor/blocks/buttons-block/

### What actually happened

The Dimensions section is missing.

### Context

User report, 5345717-zd-woothemes

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Edin

### Browser, operating system and other notes

Tested in Chrome.

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, difficult to implement

### Workaround details

The button dimensions and padding can be customized with CSS as a workaround.

### PR DESCRIPTION
**Pull request by bobmatyas**
Add support for spacing controls to Penscratch 2. I couldn't do the same for the others mentioned since they aren't in the `themes` repo. 

##### Before

Screenshot on 2022-08-08 at 13-47-49

##### After

Screenshot on 2022-08-08 at 13-51-36

Screenshot on 2022-08-08 at 13-57-57

#### Related issue(s):

Addresses #6155 for Penscratch 2

### CODE REVIEW

File: penscratch-2/functions.php [hunk 1]
```diff
@@ -94,6 +94,12 @@ function penscratch_2_setup() {
 		// Add support for responsive embeds.
 		add_theme_support( 'responsive-embeds' );
 
+		// Add support for responsive embeds.
+		add_theme_support( 'responsive-embeds' );
+
```
Comment (pbking) [inline penscratch-2/functions.php]: This is duplicated now.

**Review by pbking — APPROVED** [review]
