### PR TITLE
Blank Canvas: Customizer Fixes

### LINKED ISSUE #2980: Blank Canvas: Deregistered menu locations are still appearing in the Customizer
These are de-registered here, but are still showing up in the Customizer: 

https://github.com/Automattic/themes/blob/38f4d9a546cb550e1b451dc35ac746621f03b048/blank-canvas/functions.php#L79-L82

Screen Shot 2021-01-07 at 8 06 07 AM

### PR DESCRIPTION
**Pull request by kjellr**
This PR tidies up customizer options for the Blank Canvas theme: 

- It increases the priority of the `blank_canvas_remove_parent_theme_features` function, to ensure that the nav menu areas are actually removed (Fixes #2980)
- It removes the "Navigation" panel from the customizer entirely, since no menu areas are present in this theme. (I guess this doesn't disappear automatically?)  
- It removes Seedlet's widget area, so the Widgets panel should no longer appear.
- It adds a message to the top of the "Site Identity" panel, to clarify that the title and tagline will never appear on single posts and pages. 

---

## Screenshots

Before|After
---|---
Screen Shot 2021-01-07 at 2 07 51 PM|Screen Shot 2021-01-07 at 2 06 50 PM

Before|After
---|---
Screen Shot 2021-01-07 at 2 09 10 PM|Screen Shot 2021-01-07 at 2 10 54 PM

### CODE REVIEW

File: blank-canvas/functions.php [hunk 1]
```diff
@@ -71,25 +71,55 @@ function blank_canvas_setup() {
...
+}
+add_action( 'widgets_init', 'blank_canvas_remove_widgets_area', 11 );
+
+/**
+ * Remove unused custmizer settings.
+ */
+function blank_canvas_remove_customizer_settings( $wp_customize ) {
+
+	// Remove the navigation menus Customizer panel.
+	$wp_customize->get_panel( 'nav_menus' )->active_callback = '__return_false';
```
Comment (kjellr) [inline blank-canvas/functions.php:110]: I expected to be able to use something like `$wp_customize->remove_panel( 'nav_menus' )`, but it throws an error:

> Notice: WP_Customize_Manager::remove_panel was called incorrectly. Removing nav_menus manually will cause PHP warnings. Use the customize_loaded_components filter instead. Please see Debugging in WordPress for more information. (This message was added in version 4.5.0.)

The approach I used instead [comes from this thread](https://wordpress.stackexchange.com/a/225234), and seems to work in my testing.

**Comment by scruffian** [comment]
This looks good, but I note that it also removes Content Options which I think could be useful.

**Comment by kjellr** [comment]
Oh right, I forgot to mention that part! This PR doesn't explicitly remove that panel, it just removes Jetpack's "Author Bio" setting in that panel, since the theme won't display an author bio. If that is the only setting in the panel, the panel disappears on its own when it's empty.

**Comment by scruffian** [comment]
In that case I'll 🚢
