### PR TITLE
Fix Customizer Font Editing causing Site Editor WSOD

### LINKED ISSUE #5261: Blockbase: Site Editor WSOD due to malformed USER JSON
When customizing customized fonts in a Blockbase theme the USER JSON becomes malformed and causes a WSOD in the Site Editor.

## Steps to replicate

Using an older version of both Gutenberg (12.1.0) and Blockbase (2.0.6 using tag/v1.0.43) set custom fonts via the Customizer.

Note the USER JSON:

```
{
    "settings": {
        "typography": {
            "fontFamilies": [
                {
                    "fontFamily": "\"Arvo\", serif",
                    "slug": "body-font",
                    "name": "Body (Arvo)",
                    "google": "family=Arvo:ital,wght@0,400;0,700;1,400;1,700",
                    "fontSlug": "arvo"
                },
                {
                    "fontFamily": "\"Bodoni Moda\", serif",
                    "slug": "heading-font",
                    "name": "Heading (Bodoni Moda)",
                    "google": "family=Bodoni+Moda:ital,wght@0,400..900;1,400..900",
                    "fontSlug": "bodoni-moda"
                }
            ]
        }
    },
    "isGlobalStylesUserThemeJSON": true,
    "version": 1
}
```

Upgrade Gutenberg to 12.2.0 and Blockbase to 2.0.9 (tag/v1.0.46)

Attempt to customize the fonts again.  

Note that the USER JSON is now malformed.  ("0" and "1" are unexpected)

```
{
    "settings": {
        "typography": {
            "fontFamilies": {
                "0": {
                    "fontFamily": "\"Arvo\", serif",
                    "slug": "body-font",
                    "name": "Body (Arvo)",
                    "google": "family=Arvo:ital,wght@0,400;0,700;1,400;1,700",
                    "fontSlug": "arvo"
                },
                "1": {
                    "fontFamily": "\"Bodoni Moda\", serif",
                    "slug": "heading-font",
                    "name": "Heading (Bodoni Moda)",
                    "google": "family=Bodoni+Moda:ital,wght@0,400..900;1,400..900",
                    "fontSlug": "bodoni-moda"
                },
                "custom": [
                    {
                        "fontFamily": "\"Courier Prime\", serif",
                        "slug": "body-font",
                        "name": "Body (Courier Prime)",
                        "google": "family=Courier+Prime:ital,wght@0,400;0,700;1,400;1,700",
                        "fontSlug": "courier-prime"
                    },
                    {
                        "fontFamily": "\"Domine\", serif",
                        "slug": "heading-font",
                        "name": "Heading (Domine)",
                        "google": "family=Domine:wght@400..700",
                        "fontSlug": "domine"
                    }
                ]
            }
        }
    },
    "isGlobalStylesUserThemeJSON": true,
    "version": 1
}
```
Open the Site Editor.  Note the WSOD.

This seems to have caused the WSOD where the JSON persisted was derived from the old stored font JSON but (attempted to be) stored in the new format.

The correct format (and what is saved via the customizer when edited with an UNCUSTOMIZED theme instance using Gutenberg 12.2 and Blockbase 2.0.9) should be:

```
{
    "settings": {
        "typography": {
            "fontFamilies": {
                "custom": [
                    {
                        "fontFamily": "\"Arvo\", serif",
                        "slug": "body-font",
                        "name": "Body (Arvo)",
                        "google": "family=Arvo:ital,wght@0,400;0,700;1,400;1,700",
                        "fontSlug": "arvo"
                    },
                    {
                        "fontFamily": "\"Bodoni Moda\", serif",
                        "slug": "heading-font",
                        "name": "Heading (Bodoni Moda)",
                        "google": "family=Bodoni+Moda:ital,wght@0,400..900;1,400..900",
                        "fontSlug": "bodoni-moda"
                    }
                ]
            }
        }
    },
    "isGlobalStylesUserThemeJSON": true,
    "version": 1
}
```

## Result

WSOD 

## Expected

Correctly formatted JSON.
No WSOD for site editor.

### PR DESCRIPTION
**Pull request by pbking**
Fixes #5261 
See that for details on how to reproduce.

#### Changes proposed in this Pull Request:

Clear fontFamilies data to ensure what is posted is always correct (without tag-along `["0"]` and `["1"]` items.  

Refactored unset_property_if_it_exists() as it wasn't removing the fontFamilies Array as expected

Note... I'm still not sure where the `["0"] and ["1"]` items are coming from...  But this removes them and then everything works...

Once the fix is in place anyone experiencing the WSOD should be able to save font customizations in the customizer again to return their site editor to a working state.

### CODE REVIEW

File: blockbase/inc/customizer/wp-customize-fonts.php [hunk 1]
```diff
@@ -518,6 +518,8 @@ function handle_customize_save_after( $wp_customize ) {
 		$user_theme_json_post_content->version                     = 1;
 		$user_theme_json_post_content->isGlobalStylesUserThemeJSON = true;
 
+		$this->unset_property_if_it_exists( $user_theme_json_post_content->settings->typography, 'fontFamilies' );
```
Comment (scruffian) [inline blockbase/inc/customizer/wp-customize-fonts.php]: We should add a comment to explain what this is for

**Comment by scruffian** [comment]
I can't reproduce the issue but this change works fine for me.

**Comment by scruffian** [comment]
I pushed a change to get the CPT from the database using a Gutenberg function. This means that it now is an array, not an object so I had to update a lot of the code which is assuming we have an object to handle arrays.

File: blockbase/inc/customizer/wp-customize-fonts.php (hunk 1 above)
Comment (pbking) [reply blockbase/inc/customizer/wp-customize-fonts.php]: comment added.

**Comment by pbking** [comment]
> I pushed a change to get the CPT from the database using a Gutenberg function.

That change looks good to me.

**Review by scruffian — APPROVED** [review]
