### PR TITLE
Brompton: fixed header when changing color palette

### LINKED ISSUE #2815: Brompton: Header semi-circle not respecting custom colors
## Steps to replicate

Go to the Customizer and apply a custom color palette to the theme. Specifically, you need to change the Text Color color, as that also controls the header background color.

## Result

The entire header background changes to the new color, except for the bottom semi-circle, that remains on the default color:

Customizer_‹_Shift_to_the_left_—_WordPress_com

## Expected

For the entire header background, including both semi-circles, to change color.

Suspect this is being caused by the changes made in #2807. cc @MaggieCabrera 

* User report: https://wordpress.com/forums/topic/menu-bar-colors-2 and https://wordpress.com/forums/topic/glitch-on-my-brompton-themed-site/

### PR DESCRIPTION
**Pull request by MaggieCabrera**
#### Changes proposed in this Pull Request:

After yesterday's fix with #2807 I introduced a new bug when the colors of the header are changed via customizer. This change addresses that.

To test this change the colors of the header and check that all the header parts are the same color.

Most of the changes 

#### Related issue(s):

Closes #2815

### CODE REVIEW

File: brompton/inc/wpcom-colors.php [hunk 1]
```diff
@@ -293,14 +364,17 @@
...
-	// Background-color
-	array( '#colophon .footer-navigation,
+		// Background-color
+		array(
+			'#colophon .footer-navigation,
 			#colophon .site-info,
 			#masthead,
 			#masthead:before,
-			#page:before,
+			#masthead:after,
```
Comment (MaggieCabrera) [inline brompton/inc/wpcom-colors.php:377]: This is the actual change, the rest is just linting from our script.

**Review by scruffian — APPROVED** [review]
🚢
