### PR TITLE
Stewart: fixes on index, archive and search templates

### LINKED ISSUE #5411: Stewart: Archive Views (date, tag, and category) Show all Posts Instead of the Desired View
## Steps to replicate

View any date, tag, or category archive under Stewart, and it will simply load all posts.

## Result

For example, from the .org demo site, the Boat tag: https://wp-themes.com/stewart/?tag=boat

## Expected

Date archives will be date archives, tags will be tags, and categories will be categories, not a full posts list.

* User report: self-reported

### LINKED ISSUE #5606: Stewart: Archive Page Isn't Filtering By Tag/Category
### Quick summary

The archive page on the Stewart theme is showing all posts, not filtering by tag/category.

### Steps to reproduce

1. Activate the Stewart on a site with a couple posts, in different tags or categories
2. Check an archive page - a tag or category page

### What you expected to happen

The archive page should show posts only from the specific category/tag.

### What actually happened

The archive pages are showing all posts.

### Context

Reported here: 4778564-zd-woothemes

It seems to be an issue with this setting on the Query Loop block on the Archive template - it's deactivated on this theme, but only works when activated:

ArchiveTemplateIssue

### Workaround details

You need to edit the Archive template from the site editor, and enable that option shown on the screenshot above.

### PR DESCRIPTION
**Pull request by matiasbenedetto**
#### Changes proposed in this Pull Request:
Stewart theme changes:
- Move posts list markup to a pattern
- Use posts list pattern on the following template:
   - index
   - archive
   - search
- Fix query loop block from archive template
- Add search block in the search template

#### Related issue(s):
https://github.com/Automattic/themes/issues/5606
https://github.com/Automattic/themes/issues/5411

### CODE REVIEW

File: stewart/inc/block-patterns.php [hunk 1]
```diff
@@ -14,10 +14,11 @@
...
 	$block_pattern_categories = array(
-		'footer'   => array( 'label' => __( 'Footers', 'stewart' ) ),
-		'header'   => array( 'label' => __( 'Headers', 'stewart' ) ),
-		'pages'    => array( 'label' => __( 'Pages', 'stewart' ) ),
-		'sidebar'   => array( 'label' => __( 'Sidebars', 'stewart' ) ),
+		'footer'     => array( 'label' => __( 'Footers', 'stewart' ) ),
+		'header'     => array( 'label' => __( 'Headers', 'stewart' ) ),
+		'pages'      => array( 'label' => __( 'Pages', 'stewart' ) ),
+		'sidebar'    => array( 'label' => __( 'Sidebars', 'stewart' ) ),
+		'posts-list' => array( 'label' => __( 'Posts lists', 'stewart' ) ),
```
Comment (MaggieCabrera) [inline stewart/inc/block-patterns.php]: I think we should be using the Query category from core, since this pattern is for the query block

**Review by MaggieCabrera — APPROVED** [review]
Great work! besides the category name change, this looks good to me
