### PR TITLE
Canard: Fix editor block styles

### LINKED ISSUE #4761: Canard: Add block CSS to the editor so that colors work as expected
## Steps to replicate

Details of the issue in https://github.com/Automattic/wp-calypso/issues/54990#issuecomment-918663564

1. Confirm that the issue exists with Canard as well.
2. Apply the Rebalance fix and see if that solves the issue.

## Related Issues:

https://github.com/Automattic/wp-calypso/issues/54990#issuecomment-918663564
https://github.com/Automattic/themes/pull/4756

### PR DESCRIPTION
**Pull request by danieldudzic**
Closes #4761

### CODE REVIEW

File: canard/functions.php [hunk 1]
```diff
@@ -306,6 +306,7 @@ function canard_scripts() {
  */
 function canard_editor_styles() {
 	wp_enqueue_style( 'canard-editor-block-style', get_template_directory_uri() . '/editor-blocks.css' );
+	wp_enqueue_style( 'canard-block-style', get_template_directory_uri() . '/blocks.css' );
```
Comment (scruffian) [inline canard/functions.php:308]: I think its probably better to enqueue this before the editor styles so that if they ever target the same selectors the editor styles win.

Comment (danieldudzic) [reply canard/functions.php:308]: Thanks for 👀 - changed!

**Comment by scruffian** [comment]
This works for me on the editor, but not on the front end.

**Comment by danieldudzic** [comment]
@scruffian Would you mind sharing a bit more info on how you are testing?

It seems to be working fine for me:

About_–_themes_and_Edit_Page_‹_themes_—_WordPress

**Comment by scruffian** [comment]
I've tried testing locally and on wordpress.com:
Screenshot 2021-10-09 at 09 00 48

**Comment by scruffian** [comment]
I think this needs a Gutenberg fix: https://github.com/WordPress/gutenberg/pull/35514

**Comment by scruffian** [comment]
In my testing, this is no longer needed when running GB trunk

**Comment by danieldudzic** [comment]
I can't verify that it works correctly, as I can't get Canard to display the **Text Color** setting:
68747470733a2f2f642e70722f692f51337276456e2b

**Comment by scruffian** [comment]
I believe that the setting has moved underneath Highlight - there's a text color option there...

**Comment by danieldudzic** [comment]
> I believe that the setting has moved underneath Highlight - there's a text color option there...

I was wondering that. Thank you for clarifying.

So just to double-check, you're saying that with the latest Gutenberg trunk the Highlight Text color works correctly both in the editor and the page?

**Comment by scruffian** [comment]
Yeah, it does for me.

**Comment by scruffian** [comment]
@danieldudzic does it work for you?

**Comment by danieldudzic** [comment]
I am running the latest version of Gutenberg trunk (re-compiled) and the latest version of Canard locally and I get:

About_–_themes_and_Edit_Page_‹_themes_—_WordPress

**Comment by scruffian** [comment]
Sorry, you're right in the editor, this PR is needed as well.
